### ISSUE TITLE
Various workflow and dependency issues

### ISSUE THREAD

**Issue by mawosoft** [mawosoft/MissingCoverage#48]
Issues in MEB that apply here as well:
- [x] mawosoft/Mawosoft.Extensions.BenchmarkDotNet/issues/142
- [x] mawosoft/Mawosoft.Extensions.BenchmarkDotNet/issues/143
- [x] mawosoft/Mawosoft.Extensions.BenchmarkDotNet/issues/145
- [x] mawosoft/Mawosoft.Extensions.BenchmarkDotNet/issues/146
