### ISSUE TITLE
TODO: CI Build failure and test failures

### ISSUE THREAD

**Issue by mawosoft** [mawosoft/MissingCoverage#9]
- [x] netcoreapp3.1: `Enum.IsDefined<TEnum>` not available. Plus other net31 compat issues.
https://github.com/mawosoft/MissingCoverage/blob/1d1f205a6e7cce81ca8c23c16d8c1a54063408c4/src/Mawosoft.MissingCoverage/Options.cs#L161 https://github.com/mawosoft/MissingCoverage/blob/1d1f205a6e7cce81ca8c23c16d8c1a54063408c4/src/Mawosoft.MissingCoverage/Options.cs#L182
- [x] Env variable name is `BUILD_SOURCESDIRECTORY`. Also review entire logic again.
https://github.com/mawosoft/MissingCoverage/blob/1d1f205a6e7cce81ca8c23c16d8c1a54063408c4/tests/testdata/src/TestDataDirectory.cs#L57
- [x] Tool test ~needs parameters (at least up verbosity)~ Nope. Create tests with coverage instead. Should work OOTB and default verbosity lists input files.
https://github.com/mawosoft/MissingCoverage/blob/1d1f205a6e7cce81ca8c23c16d8c1a54063408c4/.github/workflows/ci.yml#L143-L145
